### ISSUE TITLE
Error when using maven 3.2.1 and exec-maven-plugin

### ISSUE THREAD

**Issue by danalbu** [mojohaus/exec-maven-plugin#11]
Hi All,

This is the error i get after i upgraded my maven version from 3.0.3 to 3.2.1 for the project.
I was using exec-maven-plugin version 1.2.1. Now i upgraded to 1.4.0 but i still get the error attached in this partebin:
http://pastebin.com/gRC35CtK 

I am using the exec:java goal to run a validation tool. All works with maven 3.0.3 but when i switch to 3.2.1 i get this error.
I hope you can help me in determining what the problem is.
.

**Comment by khmarbaise** [comment]
Based on the error message:

Caused by: java.lang.IllegalArgumentException: argument type mismatch
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)

I would like to see the pom file you have used...

**Comment by danalbu** [comment]
This is the piece of code that runes the plugin:

<plugin>
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>exec-maven-plugin</artifactId>
	<version>1.2.1</version>

	<dependencies>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>validator</artifactId>
			<version>${validator.version}</version>
		</dependency>	
	</dependencies>
	<executions>
		<execution>
			 <id>exec validations</id>
			 <phase>${validation.phase}</phase>
			 <goals>
							<goal>java</goal>
			 </goals>

			 <configuration>
							<mainClass>org.validator.cli.Main</mainClass>
							<includePluginDependencies>true</includePluginDependencies>
							<includeProjectDependencies>false</includeProjectDependencies>

							<executableDependency>
										   <groupId>${project.groupId}</groupId>
										   <artifactId>validator</artifactId>
							</executableDependency>

							<arguments>
							   <argument>validate</argument>
							   <argument>--jar</argument>
							   <argument>${project.build.directory}/${project.name}-${project.version}.jar</argument>
							   <argument>--type</argument>
							   <argument>validation,description</argument>
							</arguments>											
			 </configuration>
		</execution>	
	</executions>
</plugin>

**Comment by khmarbaise** [comment]
Can you give a full execution example...cause i don't know what the values are for all those properties...It seemed to be related to the version which might be a version range based on the error message but currently i can only guess.......Best would be having a full working example which is failed....with example command...so i can reproduce it?...

**Comment by danalbu** [comment]
Hi Karl,

HAPPY NEW YEAR

Sorry for the late reply. I was on hiatus for a bit.

Attached you will find 2 projects with witch you can test the error that i
mentioned:
https://drive.google.com/file/d/0Bz-Fcul2jr5KZXZ1TWVHQkxnMms/view?usp=sharing


You will need:

maven 3.2.1
zulu jdk 7 or 8 | or java jdk 7 or 8

1. build Validation so it will create the jar that you will use for
validation.
2. build Project and you will see the error.

I also included the stacktrace from when i run it locally.

From what i could figure out, with the help of a dear colleague of mine, is
that I use the maven core 3.2.1 as dependency. (comes as third-party)
If i exclude out this dependency the plugin works as expected.

Only issue is that i* need* that dependency.

Do you think you can figure out what the issue is?

P.S. Please rename the file to test.rar .
P.S.S. Second attempt mail :)

Sorry for the log email,

With respect,
Dan Albu

**Comment by khmarbaise** [comment]
It would be simpler to use default packaging formats like zip, tar.gz instead of rar......nevertheless the question is why do you need a dependency to maven-core ? And in particular for what purposes ? May be it would be a better idea to write a maven plugin....The validation you are doing is what kind of ? May be it would be an alternative to about an maven-enforcer rule?

I see at the moment several issues...First you validation project uses a maven-core dependencies which you are also packaging into a jar-with-dependencies but you use the default pom which contains the references to maven-core so in consequence also the transitive dependencies of maven-core (in the particular version) which you put on the plugin's classpath which cause class loading issues...

Furthermore the problem is located by using the dependency maven-core which interferes with the dependencies already on the classpath of exec-maven-plugin (this would be true for every maven plugin) which causes problems...

So i don't see at the moment any kind of solution, cause i don't know any kind of background why you need maven-core in your project...So may be you can give more details.....

**Comment by danalbu** [comment]
1)    1.  On brief, the validation tool we are using checks that the
content of a jar has a given structure and also, it checks whether some xml
files from that jar have a certain schema.

2)     2. For the sample project I sent you, maven-core dependency is not
required in the validation tool pom. But the real validation tool has a
transitive dependency to maven-core 3.2.1 which seems to be the cause for
this issue.


     The reason we are not converting this validation tool into a maven
plugin is the fact that it is also stand alone.

**Comment by khmarbaise** [comment]
Why does exist a dependency to maven-core in your "real validation" ? Validating JAR's and xml's does not require dependencies to maven-core nor does it make sense...So why do you have a dependency to maven-core...if you don't use you can exclude the transitive dependency....
