### ISSUE TITLE
Exposing additionalClasspathElements in java goal as command line parameter?

### ISSUE THREAD

**Issue by danielsuo** [mojohaus/exec-maven-plugin#51]
First of all, thanks for the great tool!

It looks like solving this issue is straightforward (haven't tried yet), but was wondering what the rationale for specifying additionalClasspathElements in the pom only was. Is there something more complex than adding the ```property``` Parameter or some consequence to exposing?

Thanks!

**Comment by inzucchi** [comment]
Hi @khmarbaise , @slawekjaranowski and Daniel @danielsuo 
It seems the fix for thi issues was reverted due to a breakage in the integration tests, based on the history above and the comment by @khmarbaise in the original Pull request [52](https://github.com/mojohaus/exec-maven-plugin/pull/52).  Any chance on getting this fixed again? additionalClasspathElements is documented as a valid optional parameter of the exec:java goal of the exec-maven-plugin on this page: https://www.mojohaus.org/exec-maven-plugin/java-mojo.html#additionalClasspathElements, but it seems it's not being used by the plugin.

**Comment by slawekjaranowski** [comment]
@inzucchi - I see that `additionalClasspathElements`  is in code - only support as cli argument was reverted.

https://github.com/search?q=repo%3Amojohaus%2Fexec-maven-plugin%20additionalClasspathElements&type=code

Please create new issue or better new PR for it.
